# Runs on any branch push except main.
name: Default Branch Push
on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    uses: francdomain/reusable-pipeline-templates/.github/workflows/java-on-any-branch-update.yml@shared/java
    secrets: inherit