name: Release Branch Push

on:
  push:
    branches:
      - "release/*"

jobs:
  ci:
    uses: francdomain/reusable-pipeline-templates/.github/workflows/java-on-release-branch.yml@shared/java
    with:
      docker-registry: "docker.io"
      docker-image-name: "francdocmain/demo-java-app"
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
      gitops-repo: "francdomain/gitops-manifests"
      gitops-branch: "main"
      gitops-values-path: "production/values/demo-java-app.yaml"
      image-pull-secret-enabled: false
      argocd-server: ${{ vars.ARGOCD_SERVER }}
      argocd-app-name: "demo-java-app"
      rollout-enabled: false
    secrets: inherit
